Rewrite of the build system for gapic update
- Update all protobuf / grPC / gapic dependencies.
- Remove dependency on pubref/rules_protobuf.
- Clean-up WORKSPACE and improve documentation.
- Rewrite generation scripts from scratch.
- Auto-generate protobuf-back coded for third-party protobuf plugins.
- Update all example projects to match the breaking changes in the
  generated APIS.

diff --git a/tools/bazel b/tools/bazel
--- a/tools/bazel
+++ b/tools/bazel
@@ -1,4 +1,14 @@
 #!/usr/bin/env bash
+# See https://brevi.link/shell-style and https://explainshell.com
+## This is a bazel script to ensure that the currently executed version of bazel is the REQUIRED version in the WORKSPACE file.
+##
+## Usage:
+##  This is used by bazel when any bazel command is called.
+##  It is the same as the copy in the everything repo.
+##
+
+set -e -u -o pipefail
+
 TOOLS_DIR="$(dirname "$0")"
 
 source "${TOOLS_DIR}"/../scripts/includes/os.sh
@@ -7,22 +17,20 @@ source "${TOOLS_DIR}"/../scripts/includes/os.sh
 # in this code block.
 # If a higher version of bazel is required, update `REQUIRED_BAZEL_VERSION` and the
 # `REQUIRED_BAZEL_SHA256` values for each platform.
-REQUIRED_BAZEL_VERSION="0.18.1"
+REQUIRED_BAZEL_VERSION="1.2.1"
 BAZEL_INSTALLATION_DIR="${HOME}/.bazel_installations/${REQUIRED_BAZEL_VERSION}"
+DOWNLOAD_CMD="curl -L -s -o bazel"
 if isLinux; then
-  REQUIRED_BAZEL_SHA256="68d4bdd3d467030561f0859765252286aae62146e8262d3981335a272b461498"
+  REQUIRED_BAZEL_SHA256="f5e21d7448419d1596ad0c5bb71fb336a0af08c832587aec394970ea56701d88"
   REQUIRED_BAZEL_SHA256CMD="sha256sum"
-  DOWNLOAD_CMD="wget -q --no-clobber -O bazel"
   BAZEL_EXE="bazel-${REQUIRED_BAZEL_VERSION}-linux-x86_64"
 elif isMacOS; then
-  REQUIRED_BAZEL_SHA256="7502a37f24f41498e0d09b95ec43be1a5a2aadc4398c5313432da8ced8584ee2"
+  REQUIRED_BAZEL_SHA256="6729be5a56e6eadf7a9112afd2d87ce348da8fca22077b882d9bb7a6f5d41d1c"
   REQUIRED_BAZEL_SHA256CMD="shasum -a 256"
-  DOWNLOAD_CMD="wget -q --no-clobber -O bazel"
   BAZEL_EXE="bazel-${REQUIRED_BAZEL_VERSION}-darwin-x86_64"
 else
-  REQUIRED_BAZEL_SHA256="5c491b74d3d11bedf6e4c62b111cd69a0d97cd1fbe2446a07aa5bb17d14dc7f0"
+  REQUIRED_BAZEL_SHA256="5b1a1077015090aec75c20b49c5f77ac9707b86f8e0b55c00e96e315f00f47cf"
   REQUIRED_BAZEL_SHA256CMD="sha256sum"
-  DOWNLOAD_CMD="curl -L -s -o bazel"
   # Windows does not have an installer but retrieves the executable directly.
   BAZEL_EXE="bazel-${REQUIRED_BAZEL_VERSION}-windows-x86_64.exe"
 fi
@@ -30,11 +38,11 @@ fi
 BAZEL_TARGET_PATH="${BAZEL_INSTALLATION_DIR}/bin/bazel"
 
 # Check if correct version is already installed.
-if [ -f "${BAZEL_TARGET_PATH}" ]; then
+if [ -x "${BAZEL_TARGET_PATH}" ]; then
   exec -a "$0" "${BAZEL_TARGET_PATH}" "$@"
 fi
 
-cat << EOM
+cat <<EOM
 =================================================
 Bazel version ${REQUIRED_BAZEL_VERSION} is not
 installed under ~/.bazel_installations
@@ -67,9 +75,8 @@ function _are_checksums_equal() {
 
 # Install correct bazel version.
 # If we don't have a local Bazel install at this point we need to retrieve the right version from GitHub.
-mkdir -p "${BAZEL_INSTALLATION_DIR}/bin/tmp"
-pushd "${BAZEL_INSTALLATION_DIR}/bin/tmp"
-rm bazel 2>/dev/null || true # Remove bazel binary if already present in tmp dir - indicates previous failed download.
+mkdir -p "${BAZEL_INSTALLATION_DIR}/bin"
+pushd "${BAZEL_INSTALLATION_DIR}/bin"
 echo "Starting download of bazel ${REQUIRED_BAZEL_VERSION}..."
 ${DOWNLOAD_CMD} "https://github.com/bazelbuild/bazel/releases/download/${REQUIRED_BAZEL_VERSION}/${BAZEL_EXE}"
 echo "Download finished."
@@ -83,9 +90,20 @@ if ! _are_checksums_equal "${CALCULATED_CHECKSUM}" "${REQUIRED_BAZEL_SHA256}"; t
 EOM
   exit 1
 fi
-# Mark downloaded file executable and move out of tmp directory.
-chmod a+x "bazel"
-mv bazel ..
+
+if [ -f "${BAZEL_TARGET_PATH}" ]; then
+  chmod a+x "${BAZEL_TARGET_PATH}"
+
+  if [ ! -x "${BAZEL_TARGET_PATH}" ]; then
+    echo "Couldn't mark bazel binary as executable."
+    echo "$(ls -l ${BAZEL_TARGET_PATH})"
+    exit 1
+  fi
+else
+  echo "Couldn't install bazel properly - executable doesn't exist."
+  echo "$(ls -l ${BAZEL_TARGET_PATH})"
+  exit 1
+fi
 popd
 
 echo "Executing downloaded bazel..."
